name: ealp_test
dependencies:
- numpy=1.20.3
- pandas=1.2.4
- libgfortran=5.0.0
- aom=3.6.0
- blas=1
- brotli-python=1.0.9
- brotlicffi=1.0.9.2
- bzip2=1.0.8
- ca-certificates=2025.7.15
- cairo=1.16.0
- certifi=2025.8.3
- cffi=1.17.1
- charset-normalizer =3.3.2
- dav1d=1.2.1
- expat=2.7.1
- fontconfig=2.14.1
- freetype =2.13.3
- fribidi=1.0.10
- gettext=0.21.0
- graphite2=1.3.14
- harfbuzz =10.2.0
- icu =73.1
- idna=3.7
- importlib_resources=6.4.0
- intel-openmp=2023.1.0
- jpeg=9e
- lcms2=2.16
- lerc=4.0.0
- libavif=1.1.1
- libcxx=19.1.7
- libdeflate=1.22
- libffi =3.4.4
- libgfortran5=11.3.0
- libglib=2.84.2
- libiconv=1.16
- libpng=1.6.39
- libtiff=4.7.0
- libwebp-base=1.3.2
- libxml2=2.13.8
- llvm-openmp=19.1.7
- lz4-c=1.9.4
- matplotlib-base=3.7.1
- mkl=2023.1.0
- mkl-service=2.4.0
- mkl_fft=1.3.8
- mkl_random=1.2.4
- mlxtend=0.23.1
- ncurses=6.5
- numpy=1.20.3
- numpy-base=1.20.3
- openjpeg =2.5.2
- openssl=3.0.17
- packaging=25.0
- pandas =1.2.4
- pcre2=10.42
- pillow =11.3.0
- pip =25.3
- pixman =0.46.4
- platformdirs  =4.3.7
- pooch=1.8.2
- pycparser=2.21
- pysocks=1.7.1
- python=3.9.23
- python-dateutil=2.9.0post0
- pytz=2025.2
- readline=8.3
- requests=2.32.4
- scipy=1.10.1
- setuptools=78.1.1
- six=1.17.0
- sqlite=3.50.2
- tbb=2021.8.0
- tk=8.6.15
- tzdata =2025c
- unicodedata2=15.1.0
- urllib3=2.5.0
- wheel=0.45.1
- xz=5.6.4
- zlib=1.2.13
- zstd=1.5.6
- pip:
  - mlxtend==0.18.0
  - pymupdf==1.18.19
  - contourpy==1.3.0
  - cycler==0.12.1
  - fonttools==4.60.2
  - importlib-resources==6.5.2
  - joblib ==1.5.3
  - kiwisolver==1.4.7
  - matplotlib==3.9.4
  - pymupdf==1.18.19
  - pyparsing==3.3.1
  - scikit-learn==1.6.1
  - threadpoolctl==3.6.0
  - zipp==3.23.0





